### PR TITLE
Add exceptions

### PR DESCRIPTION
**Pull request by sadekd**
Added exceptions frature and some updates.

### CODE REVIEW

**Comment by NoahNxT** [comment]
I'll review the PR later this night or tomorrow!

**Comment by NoahNxT** [comment]
Btw, I forgot to report it but when you add 2 opening hours fields in the same resource it changes each others values. Looks like you would have 2 components with the same id and if you change 1, the other also changes. Could you take a look at it and add it to this PR? 

PS: I have this issue with flexible content if you load at the create a opening hours field and load an extra layout via flexible content with an opening hour field in it.

**Comment by NoahNxT** [comment]
https://user-images.githubusercontent.com/58152024/148697082-5844f96d-efbd-409a-b4a0-e38d1e8da4ad.mov

So,what I've did to test it:
In an existing project I have where we use the package, I've checked out the **exceptions** branch in the **composer.json**
`"sadekd/nova-opening-hours-field": "dev-exceptions"`

Like you can see, at the bottom, the grey heading bar of exceptions (uitzonderingen in Dutch) appears but the "+" button does not work? Do I need to do something before it can work? Add a extra method to my novafield or something?

**Comment by NoahNxT** [comment]
Also, When you work with flexible content, it does weird things on create. When there are 2 OpeningHour fields, they seem to act like they have the same ID or something? When you remove 1 opening hour in the bottom one, it also removes 1 in the top.

https://user-images.githubusercontent.com/58152024/148697369-28974f37-fc78-44a0-9f69-3442be19bdae.mov

**Comment by NoahNxT** [comment]
MAYBE a disclaimer, I'm using Opening Hour field in a Nova Dependency Container. This could be maybe a bug or reason why it exception doesn't work. Just thinking out loud :) 

If you want my Nova resource, let me know and I'll send you it so you can reproduce it locally if you cant find the issue :)

**Comment by sadekd** [comment]
Testing, fixing...

About updating 2 fields on same time, this must be dependency container issue, maybe u using one instance for 2 fields, on my blank nova its ok with multiple fields.

About not adding first exception, i found this issue when exceptions arr is empty, but cannot found solution
```
    methods: {
        addException() {
            console.log(this.exceptions)
            this.$set(this.exceptions, getRandomDate(), [getRandomTimeInterval()])
            console.log(this.exceptions)
        },
```
~exception is added into data, but not rendered, saved :thinking:~

**Comment by NoahNxT** [comment]
image
Seems to be working the exceptions, but just a quick question? Why don't you use a date picker? This makes it much easier.
https://www.npmjs.com/package/vuejs-datepicker#demo

Also do you plan to add this kind of exception to this release?
https://github.com/sadekd/nova-opening-hours-field/issues/15

**Comment by sadekd** [comment]
For simplicity, maybe in next releases. Also with timepickers.

Spaties opening hours support also format MM-DD exceptions as recurrent, this is possible by datepicker?

i dont get exaclty #15, can you elaborate more? any screenshots?

**Comment by NoahNxT** [comment]
Actually it won't matter if it supports it or not. Because you can always do a conversion with moment JS to the needed format.
https://momentjs.com/

Also for example the vue datepicker I've linked up here has a format method which allows you to convert your dates to the right format
image

And with the #15 issue, this is a quick draw what I meant:
image

This will give you the possibility to add multiple opening hours but for example set the opening hours before midday as "on appointment only"

**Comment by NoahNxT** [comment]
@sadekd

**Comment by sadekd** [comment]
I sometimes work on it in the evenings, I don't know when it will be available for release.

About appointments, I think it's out of scope of this project, even libraries spatie opening hours.

**Comment by NoahNxT** [comment]
Actually appointment timeslots is available in the data object of spatie's package.

https://github.com/spatie/opening-hours/issues/186#issuecomment-1001611239

**Comment by sadekd** [comment]
Yes, but meaned as string for notes. Not bool

I have plans in future add this data=>string available in UX, but that requires switch to verbose data object.

I think you need utilize case 2, from your link with 2 openinghours sets, one for classic hours and next for appointment only and merge it on final

**Comment by sadekd** [comment]
Anyone for test? 🙂

**Comment by NoahNxT** [comment]
I'll test it later this day!

**Comment by NoahNxT** [comment]
LGTM!

**Comment by sadekd** [comment]
Latest call before merge and release v2 :tada:

**Pull request merged**
