### PR TITLE
Use Multiple OpeningHours fields on the same resource

### PR DESCRIPTION
**Pull request by NoahNxT**
Also we've changed some functions to a more Vue-ish way :) 

Don't mind the amount of commits where we changed namespaces, this was just for our local dev environment, we have reverted the namespace changes to make this PR

### CODE REVIEW

**Comment by NoahNxT** [comment]
@sadekd

**Comment by dmason30** [comment]
@NoahNxT @sadekd We forked this fix and have retested the field fully and it has fixed the issue we were having with multiple opening hours fields on create resource. We will go live with our fork but would be great if this was merged in soon! 

Many thanks for the fix! ❤️ See below for video of the issue we were getting, that this PR fixes:

https://user-images.githubusercontent.com/20278756/155179610-6ab4358b-2610-485c-a28f-0e4401165606.mp4

**Comment by NoahNxT** [comment]
@sadekd

**Comment by sadekd** [comment]
@NoahNxT It seems to me like an incomplete PR, when I look at the changes I can't actually see what you solved it. :thinking:

**Comment by dmason30** [comment]
@sadekd We have the fix from this PR running in production I can confirm it has fixed the issue. Though from the changes in the PR I assume its something to do with the changes around `randomIdentifier` but I can't see where that gets generated. Hopefully @NoahNxT can explain 😆

**Comment by sadekd** [comment]
I can easily add randomIndentifier as meta into exceptions branch, but thinkin where is the root of the problem

On my sandbox, if i use different field names(best practice), looks good
https://user-images.githubusercontent.com/6051891/156623680-0fd50064-fc6d-49db-bc8e-b50d4c89c605.mp4

from that i mean we can use field.name as randomIdentifer or not?

**Comment by NoahNxT** [comment]
@dmason30 indeed! There was actually a problem when you would use multiple openinghours fields in te same form. There were issues with the randomIdentifier but it is actually a pretty long time ago so I don't remember in detail what I've actually changed. The only thing is sure, now it works and we are also using a fork just because the fix isn't integrated yet.

**Comment by dmason30** [comment]
@sadekd Using your latest v2 release this issue still occurs but only on create. 
On update it seems to not duplicate changes which the video you linked shows. 

I am going to do a Nova 4 update this week so I will likely produce a PR for that but I might be able to figure out what the issue is and better understand these changes too so I can advise.

**Pull request closed without merging**
